(in-package #:sb-simd)

(define-scalar-records
  (u8      8   (unsigned-byte  8)                        #:unsigned-num         #:unsigned-reg)
  (u16     16  (unsigned-byte 16)                        #:unsigned-num         #:unsigned-reg)
  (u32     32  (unsigned-byte 32)                        #:unsigned-num         #:unsigned-reg)
  (u64     64  (unsigned-byte 64)                        #:unsigned-num         #:unsigned-reg)
  (s8      8   (signed-byte  8)                          #:signed-num           #:signed-reg)
  (s16     16  (signed-byte 16)                          #:signed-num           #:signed-reg)
  (s32     32  (signed-byte 32)                          #:signed-num           #:signed-reg)
  (s64     64  (signed-byte 64)                          #:signed-num           #:signed-reg)
  (f32     32  single-float                              #:single-float         #:single-reg)
  (f64     64  double-float                              #:double-float         #:double-reg)
  (c64     64  (complex single-float)                    #:complex-single-float #:complex-single-reg)
  (c128    128 (complex double-float)                    #:complex-double-float #:complex-double-reg)
  (u8vec   64  (simple-array (unsigned-byte 8) (*))      #:simple-array-unsigned-byte-8)
  (u16vec  64  (simple-array (unsigned-byte 16) (*))     #:simple-array-unsigned-byte-16)
  (u32vec  64  (simple-array (unsigned-byte 32) (*))     #:simple-array-unsigned-byte-32)
  (u64vec  64  (simple-array (unsigned-byte 64) (*))     #:simple-array-unsigned-byte-64)
  (s8vec   64  (simple-array (signed-byte 8) (*))        #:simple-array-signed-byte-8)
  (s16vec  64  (simple-array (signed-byte 16) (*))       #:simple-array-signed-byte-16)
  (s32vec  64  (simple-array (signed-byte 32) (*))       #:simple-array-signed-byte-32)
  (s64vec  64  (simple-array (signed-byte 64) (*))       #:simple-array-signed-byte-64)
  (f32vec  64  (simple-array single-float (*))           #:simple-array-single-float)
  (f64vec  64  (simple-array double-float (*))           #:simple-array-double-float)
  (c64vec  64  (simple-array (complex single-float) (*)) #:simple-array-complex-single-float)
  (c128vec 64  (simple-array (complex double-float) (*)) #:simple-array-complex-double-float))

(define-simd-records
  (u8.16  u8  128 #:simd-pack-int        #:int-sse-reg     #:%make-simd-pack-ub8        #:%simd-pack-ub8s)
  (u16.8  u16 128 #:simd-pack-int        #:int-sse-reg     #:%make-simd-pack-ub16       #:%simd-pack-ub16s)
  (u32.4  u32 128 #:simd-pack-int        #:int-sse-reg     #:%make-simd-pack-ub32       #:%simd-pack-ub32s)
  (u64.2  u64 128 #:simd-pack-int        #:int-sse-reg     #:%make-simd-pack-ub64       #:%simd-pack-ub64s)
  (s8.16  s8  128 #:simd-pack-int        #:int-sse-reg     #:%make-simd-pack-sb8        #:%simd-pack-sb8s)
  (s16.8  s16 128 #:simd-pack-int        #:int-sse-reg     #:%make-simd-pack-sb16       #:%simd-pack-sb16s)
  (s32.4  s32 128 #:simd-pack-int        #:int-sse-reg     #:%make-simd-pack-sb32       #:%simd-pack-sb32s)
  (s64.2  s64 128 #:simd-pack-int        #:int-sse-reg     #:%make-simd-pack-sb64       #:%simd-pack-sb64s)
  (f32.4  f32 128 #:simd-pack-single     #:single-sse-reg  #:%make-simd-pack-single     #:%simd-pack-singles)
  (f64.2  f64 128 #:simd-pack-double     #:double-sse-reg  #:%make-simd-pack-double     #:%simd-pack-doubles)
  (u8.32  u8  256 #:simd-pack-256-int    #:int-avx2-reg    #:%make-simd-pack-256-ub8    #:%simd-pack-256-ub8s)
  (u16.16 u16 256 #:simd-pack-256-int    #:int-avx2-reg    #:%make-simd-pack-256-ub16   #:%simd-pack-256-ub16s)
  (u32.8  u32 256 #:simd-pack-256-int    #:int-avx2-reg    #:%make-simd-pack-256-ub32   #:%simd-pack-256-ub32s)
  (u64.4  u64 256 #:simd-pack-256-int    #:int-avx2-reg    #:%make-simd-pack-256-ub64   #:%simd-pack-256-ub64s)
  (s8.32  s8  256 #:simd-pack-256-int    #:int-avx2-reg    #:%make-simd-pack-256-sb8    #:%simd-pack-256-sb8s)
  (s16.16 s16 256 #:simd-pack-256-int    #:int-avx2-reg    #:%make-simd-pack-256-sb16   #:%simd-pack-256-sb16s)
  (s32.8  s32 256 #:simd-pack-256-int    #:int-avx2-reg    #:%make-simd-pack-256-sb32   #:%simd-pack-256-sb32s)
  (s64.4  s64 256 #:simd-pack-256-int    #:int-avx2-reg    #:%make-simd-pack-256-sb64   #:%simd-pack-256-sb64s)
  (f32.8  f32 256 #:simd-pack-256-single #:single-avx2-reg #:%make-simd-pack-256-single #:%simd-pack-256-singles)
  (f64.4  f64 256 #:simd-pack-256-double #:double-avx2-reg #:%make-simd-pack-256-double #:%simd-pack-256-doubles))
