(in-package #:sb-simd-common)

(sb-simd-test-suite:define-aref-test u8-aref  (unsigned-byte 8) 1)
(sb-simd-test-suite:define-aref-test u16-aref (unsigned-byte 16) 1)
(sb-simd-test-suite:define-aref-test u32-aref (unsigned-byte 32) 1)
(sb-simd-test-suite:define-aref-test u64-aref (unsigned-byte 64) 1)
(sb-simd-test-suite:define-aref-test s8-aref  (signed-byte 8) 1)
(sb-simd-test-suite:define-aref-test s16-aref (signed-byte 16) 1)
(sb-simd-test-suite:define-aref-test s32-aref (signed-byte 32) 1)
(sb-simd-test-suite:define-aref-test s64-aref (signed-byte 64) 1)
(sb-simd-test-suite:define-aref-test f32-aref single-float 1)
(sb-simd-test-suite:define-aref-test f64-aref double-float 1)
